apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-pv
spec:
  storageClassName: fast-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/cache-data
