apiVersion: v1
kind: LimitRange
metadata:
  name: dataflow-limits
  namespace: dataflow
spec:
  limits:
  - type: Container
    min:
      cpu: "10m"
      memory: "10Mi"
    max:
      cpu: "2000m"
      memory: "2Gi"
    default:
      cpu: "100m"
      memory: "256Mi"
    defaultRequest:
      cpu: "50m"
      memory: "128Mi"
  - type: Pod
    min:
      cpu: "10m"
      memory: "10Mi"
    max:
      cpu: "4000m"
      memory: "4Gi"
