apiVersion: v1
kind: ResourceQuota
metadata:
  name: dataflow-quota
  namespace: dataflow
spec:
  hard:
    requests.cpu: "4"
    limits.cpu: "8"
    requests.memory: 8Gi
    limits.memory: 16Gi
    pods: "20"
