apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  application.properties: |
    spring.profiles.active=production
    logging.level.com.ecommerce=WARN
    management.endpoints.web.exposure.include=health,info
    spring.jpa.show-sql=false
