apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DATABASE_USER: cHJvZF91c2Vy
  DATABASE_PASSWORD: c3VwZXJfc2VjdXJlX3Bhc3N3b3JkNDU2
  API_SECRET_KEY: cHJvZC1zZWNyZXQta2V5LTY3ODkw
