apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
      tier: secure
  template:
    metadata:
      labels:
        app: payment-service
        tier: secure
    spec:
      containers:
      - name: httpd
        image: httpd:alpine
        ports:
        - containerPort: 3004
