apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
      tier: business
  template:
    metadata:
      labels:
        app: product-service
        tier: business
    spec:
      containers:
      - name: httpd
        image: httpd:alpine
        ports:
        - containerPort: 3002
