apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
      tier: business
  template:
    metadata:
      labels:
        app: user-service
        tier: business
    spec:
      containers:
      - name: httpd
        image: httpd:alpine
        ports:
        - containerPort: 3001
