apiVersion: batch/v1
kind: CronJob
metadata:
  name: conditional-job
spec:
  schedule: "*/5 * * * *"  # Каждые 5 минут
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: conditional-runner
            image: busybox
            command: ["sh", "-c", "if wget -q --spider http://api-server-service:8080/data/ready; then echo 'Processing data'; exit 0; else echo 'No data available'; exit 1; fi"]
          restartPolicy: OnFailure
