apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-monitor
spec:
  containers:
  - name: event-monitor
    image: curlimages/curl
    command: ["sh", "-c", "while true; do curl -s --connect-timeout 5 -H 'Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)' https://kubernetes.default/api/v1/events?watch=true; echo 'Reconnecting...'; sleep 5; done"]
    volumeMounts:
    - name: token-volume
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readOnly: true
  volumes:
  - name: token-volume
    projected:
      sources:
      - serviceAccountToken:
          path: token
          expirationSeconds: 3600
  restartPolicy: Always
