apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  application.properties: |
    spring.profiles.active=development
    logging.level.com.ecommerce=DEBUG
    management.endpoints.web.exposure.include=*
    spring.jpa.show-sql=true
