apiVersion: v1
kind: Service
metadata:
  name: api-server-service
spec:
  selector:
    name: api-server
    component: api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
