apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
spec:
  selector:
    name: web-frontend
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
