apiVersion: apps/v1
kind: Deployment
metadata:
  name: advanced-probe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advanced-probe-app
  template:
    metadata:
      labels:
        app: advanced-probe-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        startupProbe:
          exec:
            command: ["sh", "-c", "test -f /etc/nginx/conf.d/ready.conf"]
          failureThreshold: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 80
            httpHeaders:
            - name: X-Custom-Header
              value: "HealthCheck"
            - name: Accept
              value: "application/json"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 20
