apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    name: api-server
    version: v2.2.0
    component: api
    tier: backend
    data-sensitivity: internal
spec:
  replicas: 3
  selector:
    matchLabels:
      name: api-server
      component: api
  template:
    metadata:
      labels:
        name: api-server
        version: v2.2.0
        component: api
        tier: backend
        data-sensitivity: internal
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: httpd
        image: httpd:alpine
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
