apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  labels:
    app.kubernetes.io/name: example-app
    app.kubernetes.io/instance: example-app-prod
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: datapipeline
    app.kubernetes.io/managed-by: kubernetes
    tier: backend
    data-sensitivity: internal
    backup-policy: daily
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: example-app
      app.kubernetes.io/instance: example-app-prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-app
        app.kubernetes.io/instance: example-app-prod
        app.kubernetes.io/version: "1.2.0"
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: datapipeline
        app.kubernetes.io/managed-by: kubernetes
        tier: backend
        data-sensitivity: internal
        backup-policy: daily
    spec:
      containers:
      - name: example-app
        image: example-app:1.2.0
        ports:
        - containerPort: 8080
