apiVersion: apps/v1
kind: Deployment
metadata:
  name: unhealthy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unhealthy-app
  template:
    metadata:
      labels:
        app: unhealthy-app
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "sleep 30; echo 'App started'; sleep 60; echo 'App becoming unhealthy'; exit 1"]
        readinessProbe:
          exec:
            command: ["test", "-f", "/tmp/ready"]
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command: ["test", "-f", "/tmp/alive"]
          initialDelaySeconds: 10
          periodSeconds: 10
