apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  labels:
    name: web-frontend
    version: v1.2.0
    component: frontend
    tier: frontend
    data-sensitivity: public
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: "Web interface for data upload"
    maintainer: "devops-team@company.com"
    documentation: "https://wiki.company.com/web-frontend"
    runbook: "https://runbooks.company.com/web-frontend"
spec:
  replicas: 2
  selector:
    matchLabels:
      name: web-frontend
      component: frontend
  template:
    metadata:
      labels:
        name: web-frontend
        version: v1.2.0
        component: frontend
        tier: frontend
        data-sensitivity: public
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: ["sh", "-c", "echo 'Container started' > /var/log/startup.log"]
          preStop:
            exec:
              command: ["sh", "-c", "echo 'Graceful shutdown initiated' > /var/log/shutdown.log; sleep 15"]
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
