apiVersion: v1
kind: Pod
metadata:
  name: memory-stress-test
spec:
  containers:
  - name: stress
    image: progrium/stress
    command: ["stress", "--vm", "1", "--vm-bytes", "150M", "--timeout", "60s"]
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
