apiVersion: v1
kind: Pod
metadata:
  name: test-limit-violation
  namespace: dataflow
spec:
  containers:
  - name: stress
    image: progrium/stress
    resources:
      requests:
        cpu: "3000m"
        memory: "3Gi"
