apiVersion: v1
kind: Service
metadata:
  name: api-loadbalancer
  namespace: cloudshop
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
