apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13-alpine
        env:
        - name: POSTGRES_DB
          value: "techblog"
        - name: POSTGRES_USER
          value: "bloguser"
        - name: POSTGRES_PASSWORD
          value: "blogpass123"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: blog-data-pvc
